STOP_AGE = 65
PREMIUM_ESCALATION = 0.05
SALARY_INCREASE = 0.03

OFFSET_ALPHA = 1.0
OFFSET_INVESTMENT_RETURN = 0.08

GROWTH_INVESTMENT_RETURN = 0.10
BALANCED_INVESTMENT_RETURN = 0.08
CONSERVATIVE_INVESTMENT_RETURN = 0.06

NO_OFFSET_ALPHA = 0.0
