WEEKS_PER_YEAR = 52
MAX_PROJECTION_YEARS = 99
MIN_PROPERTY_MANAGER_FEE_RATE = 0.01
MAX_PROPERTY_MANAGER_FEE_RATE = 0.20

REPAYMENT_PERIODS_PER_YEAR = {
	"weekly": 52,
	"fortnightly": 26,
	"monthly": 12,
}
